export const giscusSetup = {
  id: 'giscus-comment',
  src: 'https://giscus.app/client.js',
  'data-repo': 'yiyb0603/yiyb-blog',
  'data-repo-id': 'R_kgDOJB64hA',
  'data-category': 'Blog Comment',
  'data-category-id': 'DIC_kwDOJB64hM4CaASM',
  'data-mapping': 'title',
  'data-strict': '0',
  'data-reactions-enabled': '1',
  'data-emit-metadata': '0',
  'data-theme': 'preferred_color_scheme',
  'data-input-position': 'bottom',
  'data-lang': 'ko',
  crossorigin: 'anonymous',
  async: 'true',
};
