name: close-utterances-bot-issue

on:
  issues:
    types: [opened]

jobs:
  close-issue:
    runs-on: ubuntu-latest

    steps:
      - if: github.event.issue.user.login == 'utterances-bot'
        name: Close Issue
        uses: peter-evans/close-issue@v2
